import random
import math
from environment import Agent, Environment
from planner import RoutePlanner
from simulator import Simulator

class LearningAgent(Agent):
    """ An agent that learns to drive in the Smartcab world.
        This is the object you will be modifying. """ 

    def __init__(self, env, learning=False, epsilon=1.0, alpha=0.5):
        super(LearningAgent, self).__init__(env)     # Set the agent in the evironment 
        self.planner = RoutePlanner(self.env, self)  # Create a route planner
        self.valid_actions = self.env.valid_actions  # The set of valid actions

        # Set parameters of the learning agent
        self.learning = learning # Whether the agent is expected to learn
        self.Q = dict()          # Create a Q-table which will be a dictionary of tuples
        self.epsilon = epsilon   # Random exploration factor
        self.alpha = alpha       # Learning factor

        ###########
        ## TO DO ##
        ###########
        # Set any additional class parameters as needed
        self.try_time = 1


    def reset(self, destination=None, testing=False):
        """ The reset function is called at the beginning of each trial.
            'testing' is set to True if testing trials are being used
            once training trials have completed. """

        # Select the destination as the new location to route to
        self.planner.route_to(destination)
        
        ###########
        ## TO DO ##
        ###########
        # Update epsilon using a decay function of your choice
        # Update additional class parameters as needed
        # If 'testing' is True, set epsilon and alpha to 0

        import math
        self.try_time += 1
        if testing is True:
            self.epsilon = 0
            self.alpha = 0
        else:
            # self.epsilon = self.epsilon - 0.05
            # self.epsilon = math.pow(0.01, self.try_time)
            self.epsilon = math.exp(-(0.01 * self.try_time))  #updated

        return None

    def build_state(self):
        """ The build_state function is called when the agent requests data from the 
            environment. The next waypoint, the intersection inputs, and the deadline 
            are all features available to the agent. """

        # Collect data about the environment
        waypoint = self.planner.next_waypoint() # The next waypoint 
        inputs = self.env.sense(self)           # Visual input - intersection light and traffic
        deadline = self.env.get_deadline(self)  # Remaining deadline

        ###########
        ## TO DO ##
        ###########
        # Set 'state' as a tuple of relevant data for the agent
        # demo: ('forward', {'light': 'green', 'oncoming': 'right', 'right': 'None', 'left': right})
        # demo: ('forward', 'green', 'right', 'None', 'right')
        state = (waypoint, inputs["light"], inputs["oncoming"], inputs["right"], inputs["left"])

        return state


    def get_maxQ(self, state):
        """ The get_max_Q function is called when the agent is asked to find the
            maximum Q-value of all actions based on the 'state' the smartcab is in. """

        ########### 
        ## TO DO ##
        ###########
        # Calculate the maximum Q-value of all actions for a given state
        max_q = 0.0
        max_q_action = None
        if state in self.Q:
            pair_dict = self.Q[state]
            for key, value in pair_dict.items():
                if value > max_q:
                    max_q = value
                    max_q_action = key

        return (max_q, max_q_action)


    def createQ(self, state):
        """ The createQ function is called when a state is generated by the agent. """

        ###########
        ## TO DO ##
        ###########
        # When learning, check if the 'state' is not in the Q-table
        # If it is not, create a new dictionary for that state
        #   Then, for each action available, set the initial Q-value to 0.0
        # if state not in self.Q:

        # ('forward', {'light': 'red', 'oncoming': 'left', 'right': 'left', 'left': None}, 25)
        # ('left', 'green', None, None, None, 10)
        if self.learning is True:
            if state not in self.Q:
                self.Q[state] = {self.valid_actions[0] : 0.0, self.valid_actions[1] : 0.0, self.valid_actions[2] : 0.0, self.valid_actions[3] : 0.0}
        return


    def choose_action(self, state):
        """ The choose_action function is called when the agent is asked to choose
            which action to take, based on the 'state' the smartcab is in. """

        # Set the agent state and default action
        self.state = state
        self.next_waypoint = self.planner.next_waypoint()
        action = None

        ########### 
        ## TO DO ##
        ###########
        # When not learning, choose a random action
        # When learning, choose a random action with 'epsilon' probability
        #   Otherwise, choose an action with the highest Q-value for the current state
        import random
        if self.learning is False:
            action = self.valid_actions[random.randint(0, len(self.valid_actions) - 1)]
        if self.learning is True:
            if random.random() < self.epsilon:
                action = self.valid_actions[random.randint(0, len(self.valid_actions) - 1)]
            else:
                action = self.get_maxQ(state)[1]

        return action


    def learn(self, state, action, reward):
        """ The learn function is called after the agent completes an action and
            receives an award. This function does not consider future rewards 
            when conducting learning. """

        ###########
        ## TO DO ##
        ###########
        # When learning, implement the value iteration update rule
        #   Use only the learning rate 'alpha' (do not use the discount factor 'gamma')

        if self.learning is True:
            if state in self.Q:
                pair_dict = self.Q[state]
                # if the reward is more than the old value which matched with the current action
                # update the value with the reward
                # pair_dict[action] = reward
                pair_dict[action] = (1 - self.alpha) * pair_dict[action] + self.alpha * reward

        return


    def update(self):
        """ The update function is called when a time step is completed in the 
            environment for a given trial. This function will build the agent
            state, choose an action, receive a reward, and learn if enabled. """

        state = self.build_state()          # Get current state
        self.createQ(state)                 # Create 'state' in Q-table
        action = self.choose_action(state)  # Choose an action
        reward = self.env.act(self, action) # Receive a reward
        self.learn(state, action, reward)   # Q-learn

        return
        

def run():
    """ Driving function for running the simulation. 
        Press ESC to close the simulation, or [SPACE] to pause the simulation. """

    ##############
    # Create the environment
    # Flags:
    #   verbose     - set to True to display additional output from the simulation
    #   num_dummies - discrete number of dummy agents in the environment, default is 100
    #   grid_size   - discrete number of intersections (columns, rows), default is (8, 6)
    env = Environment(verbose=False)
    
    ##############
    # Create the driving agent
    # Flags:
    #   learning   - set to True to force the driving agent to use Q-learning
    #    * epsilon - continuous value for the exploration factor, default is 1
    #    * alpha   - continuous value for the learning rate, default is 0.5
    agent = env.create_agent(LearningAgent, learning=True, epsilon=0.5)

    
    ##############
    # Follow the driving agent
    # Flags:
    #   enforce_deadline - set to True to enforce a deadline metric
    # default flag
    # env.set_primary_agent(agent)
    env.set_primary_agent(agent, enforce_deadline=True)

    ##############
    # Create the simulation
    # Flags:
    #   update_delay - continuous time (in seconds) between actions, default is 2.0 seconds
    #   display      - set to False to disable the GUI if PyGame is enabled
    #   log_metrics  - set to True to log trial and simulation results to /logs
    #   optimized    - set to True to change the default log file name
    # default flag
    # sim = Simulator(env)
    sim = Simulator(env, update_delay=0.01, log_metrics=True, display=False, optimized=True)
    
    ##############
    # Run the simulator
    # Flags:
    #   tolerance  - epsilon tolerance before beginning testing, default is 0.05 
    #   n_test     - discrete number of testing trials to perform, default is 0
    # default flag
    # sim.run()
    sim.run(n_test=50, tolerance=0.01)


if __name__ == '__main__':
    run()

    # test_dict= {"state-1" : { "left" : 0.6, "right" : 0.3, "forward" : 0.0 }}
    #
    # state = "state-1"
    # max_q = 0.0
    # max_q_action = None
    # if state in test_dict:
    #     pair_dict = test_dict[state]
    #     for key, value in pair_dict.items():
    #         if value > max_q:
    #             max_q = value
    #             max_q_action = key
    #     print(max_q, max_q_action)